### ISSUE TITLE
[VoiceMessages] Hard crash when trying to create a thread

### ISSUE THREAD

**Issue by TheSmallBlue** [mantikafasi/AliucordPlugins#33] opened 2023-04-26 19:26 UTC
With the plugin installed and enabled, when creating a thread a hard crash occurs.

https://cdn.discordapp.com/attachments/1100864553602007091/1100866312370147358/26_04_23_16_23_40.mp4

**Comment by mantikafasi** [comment] 2023-04-26 19:31
I doubt its caused by voice messagees, can you send error log

**Comment by TheSmallBlue** [comment] 2023-04-26 19:39
Attached, though keep in mind Aliucord does say it is voicemessages, and disabling voicemessages does fix it.
[2023-04-26 16_37_03.561.txt](https://github.com/mantikafasi/AliucordPlugins/files/11336654/2023-04-26.16_37_03.561.txt)

**Comment by mantikafasi** [comment] 2023-04-26 23:38
should be fixed on new version

**Closed by mantikafasi** 2023-04-26 23:38 UTC
